### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by a-v-s** [sysprogs/esp8266-openocd#6]
It seems your permissions are wrong, thus it won't configure after clone

```
diff --git a/configure b/configure
old mode 100644
new mode 100755
diff --git a/jimtcl/autosetup/find-tclsh b/jimtcl/autosetup/find-tclsh
old mode 100644
new mode 100755
diff --git a/jimtcl/configure b/jimtcl/configure
old mode 100644
new mode 100755
```

**Comment by sysprogs** [comment]
Thanks for pointing this out. Our build process is done on Windows, so it indeed ignores the permissions. Please feel free to submit a merge request and we will accept it.

**Comment by a-v-s** [comment]
After this I ran in some more issues that prevent it from building on a Linux machine. Once it builds I'll submit a merge request.

**Comment by gschorcht** [comment]
> After this I ran in some more issues that prevent it from building on a Linux machine. Once it builds I'll submit a merge request.

Could you get the compilation working? After changing the permission and running `./configure`, the make process fails for me in `automake` with
```
Makefile.am:23: warning: wildcard $(srcdir: non-POSIX variable name
Makefile.am:23: (probably a GNU make extension)
Makefile.am: error: required file './README' not found
```
Is that a problem you also had?
